label: 'Taxonomy term'
description: 'Content belonging to a certain taxonomy term.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        tid:
          exception:
            title: All
          title: '{{ arguments.tid }}'
  page_1:
    display_title: Page
