favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://cactus.docksal/themes/custom/cactus/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  cactus: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: themes/custom/cactus/logo.png
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
